image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/agora-worker"
  tag: "v0.1.0"
environment: prod
externalSecrets:
  secretsManagerPath: agora/prod/worker

aws:
  mainAccountId: "591316257673"
  clusterName: "agora-prod"
