image:
  repository: "686566045205.dkr.ecr.us-east-1.amazonaws.com/stagecraft-api"
  tag: "develop-fad56095"

replicaCount: 1

autoscaling:
  enabled: false

environment: dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

externalSecrets:
  secretsManagerPath: stagecraft/dev/api

migration:
  enabled: true
