apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agora-webhook.fullname" . }}
  namespace: agora
  labels:
    {{- include "agora-webhook.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "agora-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agora-webhook.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.externalSecrets.secretsManagerPath }}
          envFrom:
            - secretRef:
                name: {{ include "agora-webhook.fullname" . }}-secrets
          {{- end }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
