{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: agora
  labels:
    {{- include "agora-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.aws.mainAccountId }}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.aws.mainAccountId }}:role/{{ .Values.aws.clusterName }}-agora-api"
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
{{- end }}
