image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/agora-webhook"
  tag: "v0.0.4"
environment: dev
externalSecrets:
  secretsManagerPath: agora/dev/webhook

aws:
  mainAccountId: "591316257673"
  clusterName: "agora-dev"
