replicaCount: 2

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8001

gateway:
  enabled: true
  host: "webhooks.agora.example.com"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 60

serviceAccount:
  create: true
  name: "agora-webhook"
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::353284253443:role/agora-dev-agora-webhook"

environment: dev
env:
  AWS_REGION: "us-east-1"

externalSecrets:
  secretsManagerPath: ""

livenessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: 8001
  initialDelaySeconds: 5
  periodSeconds: 10
