image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/stagecraft-webhook"
  tag: "develop-6257911d"

replicaCount: 1

autoscaling:
  enabled: false

environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

externalSecrets:
  secretsManagerPath: stagecraft/dev/webhook

aws:
  mainAccountId: "591316257673"
  clusterName: "stagecraft-dev"
