image:
  repository: "686566045205.dkr.ecr.us-east-1.amazonaws.com/stagecraft-worker"
  tag: "develop-5460c126"

replicaCount: 1

autoscaling:
  enabled: false

environment: dev

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

externalSecrets:
  secretsManagerPath: stagecraft/dev/worker
