image:
  repository: "686566045205.dkr.ecr.us-east-1.amazonaws.com/stagecraft-mcp-github"
  tag: "develop-ae62fb3a"

replicaCount: 1

environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

externalSecrets:
  secretsManagerPath: stagecraft/dev/mcp-github
