image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/agora-api"
  tag: "v0.0.28"

replicaCount: 2

environment: prod

externalSecrets:
  secretsManagerPath: agora/prod/api

gateway:
  host: "api.agora.example.com"
