image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/agora-api"
  tag: "v0.0.39"

replicaCount: 1

environment: dev

externalSecrets:
  secretsManagerPath: agora/dev/api

gateway:
  host: "api.dev.agora.example.com"
