{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agora-worker.fullname" . }}
  namespace: agora
  labels:
    {{- include "agora-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "agora-worker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker
{{- end }}
